### PR TITLE
fix(index.js): Use correct orientation when mouse enters

### PR DESCRIPTION
**Pull request by an4ger**
getPosition has to be called before first setting the state (and thus rendering the tooltip) when
mouse enters, to take into account cases when the position is close to the client window edge

#388

### CODE REVIEW

**Comment by aronhelser** [comment]
This seems reasonable to me, I just need to check it out. Do you notice any different behavior on the examples?

**Comment by an4ger** [comment]
Didn't find any problem

**Comment by aronhelser** [comment]
Sorry @an4ger , I merged another PR that causes conflicts. Can you resolve them?

**Comment by aronhelser** [comment]
It checks out, thanks!

**Pull request merged**
