### PR TITLE
BREAKING CHANGE: Updating readme for demo

### PR DESCRIPTION
**Pull request by Rogger794**
Using Code sandbox for demo.

### CODE REVIEW

**Comment by markwoon** [comment]
What exactly is the breaking change?

**Comment by Rogger794** [comment]
Hi @markwoon, it was about the way it builds. It wasnt updated before.

**Comment by markwoon** [comment]
So there's no actual change in usage?  Just want to confirm.

**Comment by Rogger794** [comment]
Now it is imported as default as the example shows.

**Comment by wmertens** [comment]
Ah ok - could you perhaps explain how it was importing before so people
using the old version know how to change it?

Thanks :)

Wout.

**Pull request merged**
