### PR TITLE
Add support for borders

### PR DESCRIPTION
**Pull request by ahstro**
This adds the ability to add a one pixel border of the same color as the text by adding the `border` attribute to the JSX component, like this `<ReactTooltip border />` or `<ReactTooltip border={true} />`.
This also adds the new feature to the example page and tweaks heights accordingly.

dark-top
light-right

Also, I threw a small typo fix in there.

### CODE REVIEW

**Comment by wwayne** [comment]
I used to think users can just use the feature `class` to achieve this, but looks it would be better to support a `border` feature because it's really complicated to implement a border...

But I'd like to support in the way of `<ReactTooltip border='1px solid #fff' />` that would be easier and flexible to use, so I will do some development before merge this PR or you can keep push your thoughts.

Anyway, thanks :+1:

**Comment by ahstro** [comment]
My original thought was to do it like that as well, but I thought I'd create a basic version first, especially since you don't seem to support custom colors in any way other than custom class.

Borders around speech bubbles (specifically with the little arrow) are quite complicated, so I don't think you could support anything other than `solid` without making it insanely difficult and complex.

Let me know if you want me to keep working on this or if you want to take it from here? :)

**Comment by wwayne** [comment]
Just checked, yes it's also difficult to set the border-with on the little arrow.
maybe something like `<ReactTooltip border='#fff' />` would be better I think

**Comment by ahstro** [comment]
To me, it would make more sense to just go with these changes now for a minor release and then go for a major one where styling of the entire component is doable without custom CSS and `!important`, but if you want to I can start working on setting the border color like you mentioned above.

**Comment by wwayne** [comment]
I prefer setting the border color, then I can release after polishing some details.
I can do it if you don't time, anyway, thanks a lot :+1:

**Comment by ahstro** [comment]
Okay, go ahead.
No problem, thank you for a great component :)

**Comment by ahstro** [comment]
Nice! :) Would you mind publishing the new version to NPM?

**Comment by wwayne** [comment]
Just published in npm, there is a bug just being found, so I wanted to fix it before publishing.

**Comment by ahstro** [comment]
Ah, I see. Thanks :)

**Pull request merged**
