### PR TITLE
Changed for loop for ES5

### PR DESCRIPTION
**Pull request by andresalves**
Browser EDGE broken.

Error: Object doesn't support property or method 'ToString'

### CODE REVIEW

**Comment by OriR** [comment]
@andresalves 
Do you know if this by any chance solves #297 ?
The error is different but looks like the same piece of code.

**Comment by andresalves** [comment]
@OriR  Yes. Basically it was the same as I did.
Are you going to do the fix?

**Comment by OriR** [comment]
Unfortunately no, I ran into this PR by mistake after I noticed there was already an issue about this.
I really hope this gets merged soon!
The weird thing is that I'm using [babel transform-es2015-for-of](https://babeljs.io/docs/plugins/transform-es2015-for-of/) in my project so it should work but for some reason it doesn't...

**Comment by pemasora** [comment]
Need this changes asap. Any prevision?

**Pull request closed without merging**
