### PR TITLE
Dynamic wrapper

### PR DESCRIPTION
**Pull request by dropfen**
Adds a new prop _wrapper_.
default: "div"
supportedWrappers: span, div

Let the user define the wrapper for the Tooltip dynamically.
fixes -> #210

### CODE REVIEW

**Comment by wwayne** [comment]
I was thinking why don't just use `<span>` directly, would it be better?

**Comment by dropfen** [comment]
Well, yeah you can use *span* as the default, but it could mean some upgrading issues, for people who are rendering `divs` in production. It's safer to keep div as the default.

**Comment by MatanBobi** [comment]
After reviewing this PR and its result,
I keep getting <wrapper> elements inside my html.
I think that its because of this:

[https://github.com/dropfen/react-tooltip/blob/25aa42a2b8113aff21bb053f309d7ace9b937f93/src/index.js#L428](url)

React doesnt render the variable wrapper as a div/span but as a DOM element.
I think its because that the variable isnt with capital letter so react doesnt see it as a component.

**Comment by huumanoid** [comment]
Yes, you are right! Thank you for your review!
Babel react preset treats `wrapper` as a tag name, not as a component.
https://github.com/wwayne/react-tooltip/blob/master/standalone/react-tooltip.js#L843

If you change `wrapper` to `Wrapper`, everything is fine.
Could you make a PR, please?

Also, take a note that there is a linter error.
```
~/github/react-tooltip/src/index.js
  441:9  error  Empty components are self-closing  react/self-closing-comp
```

**Pull request merged**
