### PR TITLE
Workaround for fixed elements inside transformed elements

### PR DESCRIPTION
**Pull request by nd0ut**
Ref #16

### CODE REVIEW

**Comment by wwayne** [comment]
Could you introduce background about your thought? I see there is an new attribute `checkParentTransform`, and what you use this attribute to do?

**Comment by nd0ut** [comment]
@wwayne Yeah, sorry. The main idea is that the tooltip will scan it's own parent chain for the elements being transformed with css transform. I there is such element then the tooltip will be positioned relative to that element.

And I think it should be enabled by default. And I forgot why I did that new prop :smile:

**Comment by danbrianwhite** [comment]
@wwayne Any updates on merging this pull request? The update by @nd0ut fixes an issue I have with tooltip position in a fixed element.

**Comment by wwayne** [comment]
Sorry I've forgotten this... could you please resolve the conflict so that I can merge this in the future?

**Comment by nd0ut** [comment]
Hmm it seems I'v did something wrong. There are some strange changes after building.

**Comment by wwayne** [comment]
@nd0ut Never mind, I will fix it. But I need to check the code first... anyway, thanks for your PR

**Comment by wwayne** [comment]
@nd0ut Thanks, will do some modification before next release 👍

**Pull request merged**
