### PR TITLE
fix: add styles for shadow dom

### LINKED ISSUE #597: Base stylesheet and the Shadow DOM
Hi, I'm curious if there is a way to either:
- Change the target of the base stylesheet to be a Shadow DOM element, or
- Prevent the insertion of the base stylesheet into the `<head>` tag (and handle it manually)

I noticed you added Shadow DOM element support in `4.0.2`, but the base styles are not applying to elements within a Shadow root. Maybe I've missed something in the docs?

These are the styles I'm referring to:

image

For now I've manually added those base styles into my Shadow root and that's working decently, but the styles are still being added to the `<head>` unnecessarily.

Thanks!

### PR DESCRIPTION
**Pull request by sumthief**
fix #597

### CODE REVIEW

**Comment by sumthief** [comment]
Hey @roggervalf @aronhelser
Can you review this one please?

**Comment by aronhelser** [comment]
Looks good! Can you change your commit message so semantic-release will pick up the change? start like this:

fix(styles): ....

**Comment by sumthief** [comment]
Sorry for delay

Done :slightly_smiling_face:

**Review by roggervalf — APPROVED** [review]
LGTM, sorry for the delay, thank you @sumthief

**Pull request merged**
