### PR TITLE
Using rollup for building the project, and modifying example

### PR DESCRIPTION
**Pull request by Rogger794**
Hi @wwayne,
I refactored how to build the project by using rollup. So first run the script yarn build. If you would like to try the example, enter into example folder and run yarn to install the dependencies; I add a link to the actual package and the run yarn start. I would like to be a maintainer. I already use this package into one of my packages. https://www.npmjs.com/settings/rogger.794/packages.
I opened for feedbacks.

### CODE REVIEW

**Comment by aronhelser** [comment]
Hi @Rogger794 , thanks for your interest! I think it would be great to have you help maintain the project, sorry I haven't had time to look yet.

**Comment by aronhelser** [comment]
Can you look at Travis and see what the CI should run?

**Comment by Rogger794** [comment]
Hi @aronhelser 
I already changed travis to use yarn and use rollup build.

**Comment by aronhelser** [comment]
@Rogger794 I'm sorry I let this sit. Would you take a look at https://github.com/wwayne/react-tooltip/pull/536 and see what you think of this alternate build method? I am open to either way, but I am not familiar with rollup.

**Comment by aronhelser** [comment]
@wwayne for some reason I can't access the 'settings' tab of this repo to give @Rogger794 any permissions. Would you be willing to add them as a maintainer?

**Comment by tkalliom** [comment]
Commenting here to potentially help someone with the same problem.

After patch-level updates to dependencies, TypeScript transpilation of an app failed with `"export 'rebuild' (imported as 'ReactTooltip') was not found in 'react-tooltip'`. This change introduces EcmaScript module exports, so old, CommonJS style imports need to be changed.

It would make sense to mention a change like this in the release notes. Even a minor version change, as opposed to patch version, might be warranted. At the time of writing, `@types/react-tooltip` has not been updated accordingly.

**Comment by wwayne** [comment]
@aronhelser Sorry just saw your comment, I just added @Rogger794 into the collaborators, thank you both :)

**Pull request merged**
