### PR TITLE
React 16 support

### PR DESCRIPTION
**Pull request by mikecousins**

### CODE REVIEW

**Comment by Kerumen** [comment]
This won't suffice. See https://github.com/wwayne/react-tooltip/issues/342.
The code needs to be updated as well.

**Comment by mikecousins** [comment]
Yup, just realized that.

**Comment by plemarquand** [comment]
@mikecousins @Kerumen #342 was not a code issue, it stems from having 2 versions of react installed.

**Comment by valmassoi** [comment]
+1 would be nice to merge so the warnings are killed

**Comment by Jascha-Sundaresan** [comment]
Please merge this

**Comment by wwayne** [comment]
@mikecousins thanks, merging

**Pull request merged**
